CREATE DATABASE QuanLyNhaHang;
GO

USE QuanLyNhaHang;
GO

CREATE TABLE KhachHang
(
    MAKH           VARCHAR(10),
    NGAYDK         DATE,
    SODIEMTICHLUY  INT,

    CONSTRAINT PK_KhachHang PRIMARY KEY(MAKH),

    CONSTRAINT CHK_KhachHang_SODIEMTICHLUY CHECK ( SODIEMTICHLUY > 0 )
)
GO

CREATE TABLE Category
(
    CATEGORYID        VARCHAR(10),
    CATEGORYNAME      NVARCHAR(100),
    PARENTCATEGORYID  VARCHAR(10),

    CONSTRAINT PK_Category PRIMARY KEY(CATEGORYID),

    CONSTRAINT FK_Category FOREIGN KEY (PARENTCATEGORYID) REFERENCES Category(CATEGORYID)
)
GO



CREATE TABLE MonAn
(
    MAMON       VARCHAR(10),
    TENMON      NVARCHAR(100),
    ANH         NVARCHAR(100),
    MOTA        NVARCHAR(255),
    TAGTINHCHAT NVARCHAR(50),
    TAGMUCDICH NVARCHAR(50),
    GIA         DECIMAL,
    CATEGORYID  VARCHAR(10),

    CONSTRAINT PK_MonAn PRIMARY KEY(MAMON),

    CONSTRAINT FK_MonAn_Category FOREIGN KEY(CATEGORYID) REFERENCES Category(CATEGORYID),

    CONSTRAINT CHK_MonAn_GIA CHECK ( GIA > 0)
)
GO


CREATE TABLE ComBoCT
(
   MACOMBO     VARCHAR(10),
   MAMON       VARCHAR(10),
   SOLUONG     INT,

   CONSTRAINT PK_ComBoCT PRIMARY KEY (MACOMBO, MAMON),

   CONSTRAINT FK_ComBoCT1 FOREIGN KEY (MACOMBO) REFERENCES MonAn(MAMON),
   CONSTRAINT FK_ComBoCT2 FOREIGN KEY (MAMON) REFERENCES MonAn(MAMON),

   CONSTRAINT FK_ComBoCT_SOLUONG CHECK ( SOLUONG > 0 )
)
GO

CREATE TABLE Ban
(
   MABAN     VARCHAR(10),
   SUCCHUA   INT, 
   TRANGTHAI NVARCHAR(20) DEFAULT N'Trống',

   CONSTRAINT PK_Ban PRIMARY KEY(MABAN)
)
GO

CREATE TABLE HoaDon
(
    MAHD              VARCHAR(10),
    MABAN             VARCHAR(10),
    MAKH              VARCHAR(10),
    NGAYTL            DATETIME,
    GIOVAO            DATETIME,
    GIORA             DATETIME,
    TAMTINH           DECIMAL,
    GIAMGIA           DECIMAL DEFAULT 0,
    THANHTIEN         DECIMAL,
    TRANGTHAI         NVARCHAR(20) DEFAULT N'Chưa thanh toán',
    

    CONSTRAINT PK_HoaDon PRIMARY KEY(MAHD),

    CONSTRAINT FK_HoaDon_Ban FOREIGN KEY(MABAN) REFERENCES Ban(MABAN),
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY(MAKH) REFERENCES KhachHang(MAKH)
)
GO

CREATE TABLE CTHD
(
   MAHD        VARCHAR(10),
   MAMON       VARCHAR(10),
   SOLUONG     INT,
   DONGIA      DECIMAL,
   THANHTIEN   DECIMAL
   
   CONSTRAINT PK_CTHD PRIMARY KEY(MAHD, MAMON),
  
   CONSTRAINT FK_CTHD_HoaDon FOREIGN KEY(MAHD) REFERENCES HoaDon(MAHD),
   CONSTRAINT FK_CTHD_MonAn FOREIGN KEY(MAMON) REFERENCES MonAn(MaMon)
)
GO

CREATE TABLE Voucher
(
   ID INT IDENTITY(1,1),
   MaVC AS ('VC' + RIGHT('0000' + CAST(ID AS VARCHAR(10)), 3)),
   TENVC                  NVARCHAR(50),
   SODIEMCANDOI           INT,
   SOTIENDUOCGIAM         DECIMAL,
   GIATRIHOADONTOITHIEU   DECIMAL,

   CONSTRAINT PK_Voucher PRIMARY KEY (ID),

   CONSTRAINT CHK_Voucher_SODIEMCANDOI CHECK ( SODIEMCANDOI > 0),
   CONSTRAINT CHK_Voucher_SOTIENDUOCGIAM CHECK (SOTIENDUOCGIAM > 0),
   CONSTRAINT CHK_Voucher_GIATRIHOADONTOITHIEU CHECK ( GIATRIHOADONTOITHIEU > 0 )
)
GO

CREATE TABLE LichSuDiem
(
    ID            VARCHAR(10),
    MaLS AS ('LS' + RIGHT('0000' + CAST(ID AS VARCHAR(10)), 3)),
    MAKH          VARCHAR(10) NOT NULL,
    MAHD          VARCHAR(10),
    SODIEMTHAYDOI INT NOT NULL,
    HANHDONG      NVARCHAR(15) NOT NULL,  -- Đổi điểm hoặc tích điểm
    NGAYTHUCHIEN  DATETIME DEFAULT GETDATE(),

    CONSTRAINT PK_LichSuDiem PRIMARY KEY (ID),

    CONSTRAINT FK_LichSuDiem_KhachHang FOREIGN KEY (MAKH) REFERENCES KhachHang(MAKH),
    CONSTRAINT FK_LichSuDiem_HoaDon FOREIGN KEY (MAHD) REFERENCES HoaDon(MAHD),

    CONSTRAINT CHK_LichSuDiem_HANHDONG CHECK ( HANHDONG IN (N'Đổi điểm', N'Tích điểm') ),
    CONSTRAINT CHK_LichSuDiem_SODIEMTHAYDOI CHECK ( SODIEMTHAYDOI > 0 )
)
GO


ALTER DATABASE QuanLyNhaHang SET ENABLE_BROKER;
GO








