CREATE DATABASE QuanLyNhaHang;
GO

USE QuanLyNhaHang;
GO

CREATE TABLE KhachHang
(
    MAKH           VARCHAR(10),
    NGAYDK         DATE,
    SODIEMTICHLUY  INT,

    CONSTRAINT PK_KhachHang PRIMARY KEY(MAKH)
)
GO

CREATE TABLE Category
(
    CATEGORYID        VARCHAR(10),
    CATEGORYNAME      NVARCHAR(100),
    PARENTCATEGORYID  VARCHAR(10),

    CONSTRAINT PK_Category PRIMARY KEY(CATEGORYID),

    CONSTRAINT FK_Category FOREIGN KEY (PARENTCATEGORYID) REFERENCES Category(CATEGORYID)
)
GO



CREATE TABLE MonAn
(
    MAMON       VARCHAR(10),
    TENMON      NVARCHAR(100),
    ANH         NVARCHAR(100),
    MOTA        NVARCHAR(255),
    TRANGTHAI   NVARCHAR(10),
    GIA         DECIMAL,
    CATEGORYID  VARCHAR(10),

    CONSTRAINT PK_MonAn PRIMARY KEY(MAMON),
    CONSTRAINT FK_MonAn_Category FOREIGN KEY(CATEGORYID) REFERENCES Category(CATEGORYID)
)
GO


CREATE TABLE ComBoCT
(
   MACOMBO     VARCHAR(10),
   MAMON       VARCHAR(10),
   SOLUONG     INT,

   CONSTRAINT PK_ComBoCT PRIMARY KEY (MACOMBO, MAMON),

   CONSTRAINT FK_ComBoCT1 FOREIGN KEY (MACOMBO) REFERENCES MonAn(MAMON),
   CONSTRAINT FK_ComBoCT2 FOREIGN KEY (MAMON) REFERENCES MonAn(MAMON),
)
GO

CREATE TABLE Ban
(
   MABAN     VARCHAR(10),
   SUCCHUA   INT, 
   TRANGTHAI NVARCHAR(20) DEFAULT N'Trống',

   CONSTRAINT PK_Ban PRIMARY KEY(MABAN)
)
GO

CREATE TABLE HoaDon
(
    MAHD              VARCHAR(10),
    MABAN             VARCHAR(10),
    MAKH              VARCHAR(10),
    NGAYTL            DATE,
    GIOVAO            DATETIME,
    GIORA             DATETIME,
    TAMTINH           DECIMAL,
    GIAMGIA           DECIMAL,
    THANHTIEN         DECIMAL,
    TRANGTHAI         NVARCHAR(20) DEFAULT N'Chưa thanh toán',
    GHICHU            NVARCHAR(200),
    

    CONSTRAINT PK_HoaDon PRIMARY KEY(MAHD),

    CONSTRAINT FK_HoaDon_Ban FOREIGN KEY(MABAN) REFERENCES Ban(MABAN),
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY(MAKH) REFERENCES KhachHang(MAKH)
)
GO

CREATE TABLE CTHD
(
   MAHD        VARCHAR(10),
   MAMON       VARCHAR(10),
   SOLUONG     INT,
   DONGIA      DECIMAL,
   THANHTIEN   DECIMAL
   
   CONSTRAINT PK_CTHD PRIMARY KEY(MAHD, MAMON),
  
   CONSTRAINT FK_CTHD_HoaDon FOREIGN KEY(MAHD) REFERENCES HoaDon(MAHD),
   CONSTRAINT FK_CTHD_MonAn FOREIGN KEY(MAMON) REFERENCES MonAn(MaMon)
)
GO

ALTER TABLE KhachHang DROP COLUMN SDT;


DELETE FROM KhachHang;

